name: ygb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.7

workspace: 
  - packages/ygb_sdk  
  - packages/design_system

  
dev_dependencies:
  melos: ^7.5.0
