name: ygb_sdk
resolution: workspace
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  design_system: ^0.0.1
  core: ^0.0.1
  user_connection: ^0.0.1
  

  


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
